// Maps ESPN English team display names → { name (Spanish for DB), flag emoji }
export const TEAM_MAP = {
  'Argentina':          { name: 'Argentina',          flag: '🇦🇷' },
  'Brazil':             { name: 'Brasil',              flag: '🇧🇷' },
  'Colombia':           { name: 'Colombia',            flag: '🇨🇴' },
  'Ecuador':            { name: 'Ecuador',             flag: '🇪🇨' },
  'Paraguay':           { name: 'Paraguay',            flag: '🇵🇾' },
  'Uruguay':            { name: 'Uruguay',             flag: '🇺🇾' },
  'Germany':            { name: 'Alemania',            flag: '🇩🇪' },
  'Austria':            { name: 'Austria',             flag: '🇦🇹' },
  'Belgium':            { name: 'Bélgica',             flag: '🇧🇪' },
  'Bosnia-Herzegovina': { name: 'Bosnia Herzegovina',  flag: '🇧🇦' },
  'Croatia':            { name: 'Croacia',             flag: '🇭🇷' },
  'Czechia':            { name: 'Chequia',             flag: '🇨🇿' },
  'England':            { name: 'Inglaterra',          flag: '🏴󠁧󠁢󠁥󠁮󠁧󠁿' },
  'France':             { name: 'Francia',             flag: '🇫🇷' },
  'Netherlands':        { name: 'Países Bajos',        flag: '🇳🇱' },
  'Norway':             { name: 'Noruega',             flag: '🇳🇴' },
  'Portugal':           { name: 'Portugal',            flag: '🇵🇹' },
  'Scotland':           { name: 'Escocia',             flag: '🏴󠁧󠁢󠁳󠁣󠁴󠁿' },
  'Spain':              { name: 'España',              flag: '🇪🇸' },
  'Sweden':             { name: 'Suecia',              flag: '🇸🇪' },
  'Switzerland':        { name: 'Suiza',               flag: '🇨🇭' },
  'Turkey':             { name: 'Turquía',             flag: '🇹🇷' },
  'Türkiye':            { name: 'Turquía',             flag: '🇹🇷' },
  'Australia':          { name: 'Australia',           flag: '🇦🇺' },
  'Iraq':               { name: 'Irak',                flag: '🇮🇶' },
  'Iran':               { name: 'Irán',                flag: '🇮🇷' },
  'Japan':              { name: 'Japón',               flag: '🇯🇵' },
  'Jordan':             { name: 'Jordania',            flag: '🇯🇴' },
  'South Korea':        { name: 'Corea del Sur',       flag: '🇰🇷' },
  'Qatar':              { name: 'Qatar',               flag: '🇶🇦' },
  'Saudi Arabia':       { name: 'Arabia Saudita',      flag: '🇸🇦' },
  'Uzbekistan':         { name: 'Uzbekistán',          flag: '🇺🇿' },
  'Algeria':            { name: 'Argelia',             flag: '🇩🇿' },
  'Cape Verde':         { name: 'Cabo Verde',          flag: '🇨🇻' },
  'DR Congo':           { name: 'Congo DR',            flag: '🇨🇩' },
  "Côte d'Ivoire":      { name: 'Costa de Marfil',     flag: '🇨🇮' },
  "Ivory Coast":        { name: 'Costa de Marfil',     flag: '🇨🇮' },
  'Egypt':              { name: 'Egipto',              flag: '🇪🇬' },
  'Ghana':              { name: 'Ghana',               flag: '🇬🇭' },
  'Morocco':            { name: 'Marruecos',           flag: '🇲🇦' },
  'Senegal':            { name: 'Senegal',             flag: '🇸🇳' },
  'South Africa':       { name: 'Sudáfrica',           flag: '🇿🇦' },
  'Tunisia':            { name: 'Túnez',               flag: '🇹🇳' },
  'Canada':             { name: 'Canadá',              flag: '🇨🇦' },
  'Mexico':             { name: 'México',              flag: '🇲🇽' },
  'United States':      { name: 'Estados Unidos',      flag: '🇺🇸' },
  'Curacao':            { name: 'Curazao',             flag: '🇨🇼' },
  'Curaçao':            { name: 'Curazao',             flag: '🇨🇼' },
  'Haiti':              { name: 'Haití',               flag: '🇭🇹' },
  'Panama':             { name: 'Panamá',              flag: '🇵🇦' },
  'New Zealand':        { name: 'Nueva Zelanda',       flag: '🇳🇿' },
  'Costa Rica':         { name: 'Costa Rica',          flag: '🇨🇷' },
  'Venezuela':          { name: 'Venezuela',           flag: '🇻🇪' },
  'Indonesia':          { name: 'Indonesia',           flag: '🇮🇩' },
};

export function resolveTeam(espnName) {
  return TEAM_MAP[espnName] || { name: espnName, flag: '🏳' };
}
